---
- name: yum install package (Cybereason EDR)
  hosts: all
  become: yes
  tasks:
    - name: yum install package (Cybereason EDR)
      yum:
        name:
          - zlib-devel
          - bzip2-devel
          - openssl-devel
          - ncurses-devel
          - sqlite-devel
          - readline-devel
          - tk-devel
          - gdbm-devel
          - db4-devel
          - xz-devel
        state: latest
