---
- name: firewalld add service http httpd
  hosts: all
  become: yes
  
  vars:
    port: 5050/tcp
    state: enabled  # enabled: open, disabled: close
  
  
  tasks:
    - name: firewalld permits access to http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: firewalld permits access to https service
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: yes
    
    - name: set the port state(gitlab registory)
      firewalld: permanent=True port={{ port }} state={{ state }}
      notify: reload firewalld
      when: firewalld_result.stdout == "active"
      
      
    - name: firewalld reload
      command: firewall-cmd --reload
