---
- name: gitlab-ctl reconfigure
  hosts: all
  become: yes
  tasks:    
    - name: Run gitlab-ctl reconfigure
      shell: gitlab_reconfigure.sh > result2.log
      args:
        chdir: /work/scripts
        
