---
- name: gitlab-ctl reconfigure
  hosts: all
  become: yes
  tasks:    
    - name: Run gitlab-ctl reconfigure.sh
      shell: ./work/scripts/gitlab_reconfigure.sh
      args:
        chdir: /work/scripts
