---
- name: gitlab-ctl reconfigure
  hosts: all
  become: yes
  tasks:    
    - name: Run gitlab-ctl create logfile
      shell: gitlab_reconfigure.sh
      args:
        chdir: /work/scripts
        
