---
- name: gitlab-ctl reconfigure
  hosts: all
  become: yes
  tasks:    
    - name: Run gitlab-ctl reconfigure.sh
      command:
        cmd: 'gitlab-ctl reconfigure > git-reconfigure-result.log'
        chdir: /tmp
