---
- name: gitlab password reset
  hosts: all
  become: yes
  ignore_errors: yes
  tasks:    
    - name: gitlab-rails login
      command: gitlab-rails console -e production
      
    - name: select root user
      command: user = User.find(1)
      
    - name: reset password
      command: user.password = 'password'
      
    - name: reset password confirmation
      command: user.password_confirmation='password'
      
    - name: password save
      command: user.save!
    
    - name: exit gitlab-rails
      command: exit
      
