---
- name: selinux change disabled and os reboot
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:  
    - lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
