---
- name: selinux change disabled and os reboot
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:  
    - lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
    
    - name: Reboot the machine (Wait for 2 min)
      reboot:
        reboot_timeout: 120
