---
- name: yum install package (server protet)
  hosts: all
  become: yes
  tasks:
    - name: yum install package (server protet)
      yum:
        name:
          - glibc
          - libgcc
          - zlib
          - bzip2
          - libuuid
          - libstdc++
          - nss-softokn-freebl
          - perl-Sys-Syslog
        state: latest
        
    - name: set firewalld ACL set the port state(serverprotect 14942)
      firewalld: 
        permanent: True
        port: 14942/tcp
        state: enabled
        immediate: yes
        
    - name: set the port state(serverprotect 14943)
      firewalld: 
        permanent: True
        port: 14943/tcp
        state: enabled
        immediate: yes
        
    - name: firewalld reload
      command: firewall-cmd --reload
     
    - name: get server protect module
      get_url:
        url: https://files.trendmicro.com/products/splx/SPLX30-X64-Redhat8_CentOS8_Suse15-repack3.tar.gz
        dest: /usr/local/src
         
     - name: criate folder scripts
        command: tar -xvzf SPLX30-X64-Redhat8_CentOS8_Suse15-repack3.tar.gz
      args:
        chdir: /usr/local/src

     - name: Run SProtectLinux-3.0.bin
       shell: ./SProtectLinux-3.0.bin
       args:
         chdir: /usr/local/src
     
